USER_DIR="$HOME/.config/user"
SHELL_CONFIG_PATH="$USER_DIR/src/sh"

source "$SHELL_CONFIG_PATH/aliases.sh"
source "$SHELL_CONFIG_PATH/asdf.sh"
source "$SHELL_CONFIG_PATH/bind-keys.sh"
source "$SHELL_CONFIG_PATH/functions.sh"
source "$SHELL_CONFIG_PATH/load-secrets.sh"
source "$SHELL_CONFIG_PATH/paths.sh"
source "$SHELL_CONFIG_PATH/processes.sh"
